export const events = [
    {
        id: 1,
        eventName: 'BLUSH OF ELEGANCE ACRYLIC CLASS',
        startDate: null,
        date: '2026-05-08',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78.75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly.  All supplies provided',
        img: 'IMG_5669.PNG',
        modalDescription: 'Immerse yourself in a refined, feminine composition of soft florals and glowing glass, brought to life with rich acrylic texture.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 2,
        eventName: 'BLOOMING LIGHT IN WATERCOLOR',
        startDate: null,
        date: '2026-05-13',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78.75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly.  All supplies provided',
        img: 'IMG_6510GH.PNG',
        modalDescription: 'We will explore transparent watercolor layering and soft washes to capture light, form, and the delicate glow of blooming daffodils.Some images used in our announcements are digital visual references created to illustrate the theme of the class. Final artworks created during the workshop may vary and will reflect each participant’s personal interpretation.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 3,
        eventName: 'TAKAKKAW FALLS ACRYLIC CLASS',
        startDate: null,
        date: '2026-05-15',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78.75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly.  All supplies provided',
        img: 'IMG_5612.PNG',
        modalDescription: 'Learn to paint a powerful mountain waterfall with bold palette knife textures and vibrant natural tones in an expressive acrylic style. Some images used in our announcements are digital visual references created to illustrate the theme of the class. Final artworks created during the workshop may vary and will reflect each participant’s personal interpretation.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 4,
        eventName: 'SILENT GRACE WATERCOLOR CLASS',
        startDate: null,
        date: '2026-05-20',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78.75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly.  All supplies provided',
        img: 'IMG_5594.PNG',
        modalDescription: 'Capture the elegance and gentle movement of a swan on water using soft watercolor techniques and delicate tonal transitions.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 5,
        eventName: 'MIDNIGHT IN PARIS ACRYLIC CLASS',
        startDate: null,
        date: '2026-05-22',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78.75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly.  All supplies provided',
        img: 'IMG_5667.PNG',
        modalDescription: 'Discover the magic of Paris at night with glowing lights and rich, textured acrylic strokes. Some images used in our announcements are digital visual references created to illustrate the theme of the class. Final artworks created during the workshop may vary and will reflect each participant’s personal interpretation.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 6,
        eventName: 'LILAC DREAM ACRYLIC CLASS',
        startDate: null,
        date: '2026-05-27',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78.75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly.  All supplies provided',
        img: 'IMG_5550.PNG',
        modalDescription: 'Create a dreamy lilac bloom with airy strokes, soft transitions, and vibrant spring light.Some images used in our announcements are digital visual references created to illustrate the theme of the class. Final artworks created during the workshop may vary and will reflect each participant’s personal interpretation.',
        modalIncludes: null,
        modalDiscount: null,
    },
    {
        id: 7,
        eventName: 'SUNLIT SHORE ACRYLIC CLASS',
        startDate: null,
        date: '2026-05-29',
        time: '6:00 pm - 9:00 pm',
        day: null,
        price: 78.75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'Beginner-friendly.  All supplies provided',
        img: 'IMG_5603.PNG',
        modalDescription: 'Create a glowing sunset scene with warm colors, light reflections, and easy expressive brushwork.Some images used in our announcements are digital visual references created to illustrate the theme of the class. Final artworks created during the workshop may vary and will reflect each participant’s personal interpretation.',
        modalIncludes: null,
        modalDiscount: null,
    },
];

export const infinityEvent = [
    {
        id: 1,
        eventName: 'REGULAR ART CLASSES FOR ADULTS (4 classes)',
        time: '3:00 pm - 6:00 pm',
        date: '%',
        day: 'Saturday',
        price: 231,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: 'photo.webp',
        modalDescription: "Master visual arts through group lessons designed to your interests and skill level. Explore painting, drawing, and composition at your own pace in a relaxed and supportive environment. ",
        modalIncludes: null,
        modalDiscount: "for four classes"
    },
    {
        id: 2,
        eventName: 'PRIVATE ART CLASSES',
        time: '-',
        date: '%',
        day: 'Monday - Friday',
        price: 75,
        selected: false,
        location: '1324 11 Ave SW, #202, Calgary',
        description: 'All supplies provided',
        img: 'adults.JPG',
        modalDescription: "Creativity, dreams, inspiration - the world of art awaits you! We practice a variety of techniques, materials and subjects in our classes. ",
        modalIncludes: null,
        modalDiscount: "for 1,5 hour"
    },
]
